version: 2.1

executors:
  rails-executor:
    docker:
      - image: circleci/ruby:3.3.5-slim  # Using a similar Ruby version as in your Dockerfile
        environment:
          RAILS_ENV: test
          BUNDLE_PATH: /usr/local/bundle
      - image: circleci/postgres:13.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: my_test_db  # Replace with your test database name
          POSTGRES_PASSWORD: ''

    working_directory: ~/rails

jobs:
  setup-dependencies:
    executor: rails-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update -qq && \
            sudo apt-get install --no-install-recommends -y curl libjemalloc2 libvips libpq-dev pkg-config nodejs
      - run:
          name: Bundle install
          command: bundle install --jobs=4 --retry=3

  run-tests:
    executor: rails-executor
    steps:
      - checkout
      - run:
          name: Database setup
          command: |
            bin/rails db:create db:schema:load RAILS_ENV=test
      - run:
          name: Run tests
          command: bundle exec rails test

workflows:
  version: 2
  test:
    jobs:
      - setup-dependencies
      - run-tests:
          requires:
            - setup-dependencies