version: 2.1

executors:
  rails-executor:
    docker:
      - image: cimg/ruby:3.3.5
        environment:
          RAILS_ENV: test
      - image: cimg/postgres:17.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: pi_ww_test
          POSTGRES_PASSWORD: 'eipugneqriopgn34--1'

    working_directory: ~/rails

jobs:
  setup-dependencies:
    executor: rails-executor
    environment:
      BUNDLE_PATH: $HOME/.bundle
      GEM_HOME: "$HOME/.gem"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update -qq && \
            sudo apt-get install --no-install-recommends -y curl libjemalloc2 libvips libpq-dev pkg-config nodejs
      - run:
          name: Bundle Gem
          command: gem install bundle
      - run:
          name: Create and Grant write permissions
          command: sudo mkdir -p /usr/local/bundle && sudo chown -R circleci:circleci /usr/local/bundle
      - run:
          name: Bundle install
          command: bundle install --jobs=4 --retry=3 --verbose
      - run:
          name: Bundle gem install
          command: bundle install --gemfile /home/circleci/rails/Gemfile

  run-tests:
    executor: rails-executor
    environment:
      DATABASE_USERNAME: "postgres"
      DATABASE_PASSWORD: "eipugneqriopgn34--1"
      DATABASE_HOSTNAME: "localhost"
      DATABASE_PORT: 5432
      DATABASE_URL: "postgresql://postgres@localhost/pi_ww_test"
      BUNDLE_PATH: $HOME/.bundle
      GEM_HOME: "$HOME/.gem"
    steps:
      - checkout
      - run:
          name: Database setup
          command: |
            bin/rails db:create db:schema:load
      - run:
          name: Run tests
          command: bundle exec rails test

workflows:
  version: 2
  test:
    jobs:
      - setup-dependencies
      - run-tests:
          requires:
            - setup-dependencies