jobs:
  setup-dependencies:
    docker:
      - image: cimg/ruby:3.3.5
      - image: cimg/postgres:17.0
    working_directory: ~/rails
    environment:
      BUNDLE_PATH: ~/vendor/bundle
      GEM_HOME: ~/vendor/bundle

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update -qq && \
            sudo apt-get install --no-install-recommends -y curl libjemalloc2 libvips libpq-dev pkg-config nodejs
      - run:
          name: Bundle install
          command: |
            bundle config set path '~/vendor/bundle' && \
            bundle install --jobs=4 --retry=3 --verbose
      - save_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  run-tests:
    docker:
      - image: cimg/ruby:3.3.5
      - image: cimg/postgres:17.0
    working_directory: ~/rails
    environment:
      DATABASE_USERNAME: "postgres"
      DATABASE_PASSWORD: "eipugneqriopgn34--1"
      DATABASE_URL: "postgresql://postgres@localhost/pi_ww_test"
      BUNDLE_PATH: ~/vendor/bundle
      GEM_HOME: ~/vendor/bundle

    steps:
      - checkout
      - restore_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: Database setup
          command: bundle exec rails db:create db:schema:load
      - run:
          name: Run tests
          command: bundle exec rails test
workflows:
  version: 2
  test:
    jobs:
      - setup-dependencies
      - run-tests:
          requires:
            - setup-dependencies
