# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

jobs:
  run-rails-tests:
    docker:
      - image: cimg/ruby:3.0 
      - image: circleci/postgres:13 
    
    # Define environment variables if necessary
    environment:
      RAILS_ENV: test
      POSTGRES_USER: postgres
      POSTGRES_DB: pw-test # replace with your test database name

    steps:
      - checkout
      
      # Install dependencies
      - run:
          name: Install Bundler
          command: gem install bundler
          
      - run:
          name: Bundle Install
          command: bundle install --jobs=4 --retry=3
      
      # Set up the database
      - run:
          name: Database Setup
          command: |
            bundle exec rails db:create
            bundle exec rails db:schema:load
      
      # Run Rails tests
      - run:
          name: Run Tests
          command: bundle exec rails test # Use `rspec` if you use RSpec

# Workflows to orchestrate the jobs
workflows:
  test:
    jobs:
      - run-rails-tests