default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: <%= ENV["DATABASE_DEV_DBNAME"] || "postgres://postgres@localhost:5432/ww_marketing_development" %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOSTNAME'] %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>

test:
  <<: *default
  database: <%= ENV["DATABASE_TEST_DBNAME"] || "postgres://postgres@localhost:5432/ww_marketing_test" %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOSTNAME'] %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>

production:
  <<: *default
  database: <%= ENV["DATABASE_PROD_DBNAME"] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOSTNAME'] %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
